# 基础镜像, 根据需要选择dotnet core版本
#
## 使用dotnet/core/aspnet
# FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-bionic
# FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-bionic
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic

COPY sources.bionic.list /etc/apt/sources.list

# 解决Asp.Net Core 使用System.Drawing.Common部署到docker报错问题
# https://www.cnblogs.com/sunnytrudeau/p/9384620.html
# install System.Drawing native dependencies
RUN ln -s /lib/x86_64-linux-gnu/libdl-2.27.so /lib/x86_64-linux-gnu/libdl.so
RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
        libc6-dev \
        libgdiplus \
        libx11-dev \
        libfontconfig1 \
     && ln -s libgdiplus.so gdiplus.dll

# wkhtmltopdf
COPY wkhtmltox_0.12.5-1.bionic_amd64.deb /tmp

RUN apt-get install -y fontconfig libfontenc1 x11-common xfonts-75dpi xfonts-base xfonts-encodings xfonts-utils

RUN dpkg -i /tmp/wkhtmltox_0.12.5-1.bionic_amd64.deb
RUN wkhtmltopdf -V
RUN rm -f /tmp/wkhtmltox_0.12.5-1.bionic_amd64.deb

# Fonts
COPY ./fonts/msyhbd.ttc /usr/share/fonts
COPY ./fonts/msyhl.ttc /usr/share/fonts
COPY ./fonts/msyh.ttc /usr/share/fonts
COPY ./fonts/simsunb.ttf /usr/share/fonts
COPY ./fonts/simsun.ttc /usr/share/fonts

RUN rm -rf /var/lib/apt/lists/*
