# FROM mcr.microsoft.com/dotnet/core/sdk:3.0-bionic
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-bionic

COPY ubuntu/sources.bionic.list /etc/apt/sources.list

ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet tool install --global dotnet-trace

WORKDIR /tools
